"""
Weather & Seasonal Intelligence Module (core/weather_service.py)

Provides environmental weather context and deterministic agricultural rule advisories.
Uses provider abstraction for weather data ingestion (Mock / OpenWeatherMap).
Zero LLM calls in rule engine.
"""

from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, Field


class WeatherContext(BaseModel):
    """Structured weather and environmental context model."""
    location: str = Field(default="North Central Province (Anuradhapura/Kurunegala)", description="Target agricultural zone")
    season: str = Field(default="Yala Season", description="Active cultivation season (Yala / Maha)")
    temperature_c: float = Field(default=31.0, description="Ambient temperature in Celsius")
    humidity_pct: float = Field(default=84.0, description="Relative humidity percentage")
    rainfall_probability_pct: float = Field(default=65.0, description="24-hour rainfall probability percentage")
    wind_speed_kmh: float = Field(default=14.0, description="Wind speed in km/h")


class SeasonalAdvisory(BaseModel):
    """Structured advisories generated by the deterministic rule engine."""
    fungal_risk_alert: str = Field(default="Normal", description="Fungal disease risk tier")
    fertilizer_timing_advice: str = Field(default="Normal Schedule", description="Fertilizer application timing recommendation")
    irrigation_advice: str = Field(default="Standard Water Management", description="Water management guidance")
    advisory_notes: List[str] = Field(default_factory=list, description="Detailed agricultural advisory bullet points")


class IWeatherProvider(ABC):
    """Abstract Weather Provider interface for interchangeable weather backends."""

    @abstractmethod
    def get_weather(self, location: str = "North Central Province") -> WeatherContext:
        pass


class MockSriLankanWeatherProvider(IWeatherProvider):
    """Default provider returning realistic Sri Lankan paddy field weather context."""

    def get_weather(self, location: str = "North Central Province") -> WeatherContext:
        return WeatherContext(
            location=location,
            season="Yala Season",
            temperature_c=31.5,
            humidity_pct=85.0,
            rainfall_probability_pct=70.0,
            wind_speed_kmh=12.0
        )


class SeasonAdvisor:
    """
    Deterministic Agricultural Rule Engine.
    Evaluates WeatherContext and generates targeted farming advisories without LLM calls.
    """

    @staticmethod
    def evaluate(weather: WeatherContext) -> SeasonalAdvisory:
        notes: List[str] = []
        fungal_alert = "Normal Risk"
        fert_advice = "Proceed with Standard Application"
        irrigation_adv = "Maintain Standard 2-5cm Water Depth"

        # Rule 1: High Humidity -> Fungal Disease Warning
        if weather.humidity_pct >= 80.0:
            fungal_alert = "HIGH RISK (Elevated Paddy Blast & Sheath Blight Alert)"
            notes.append("[WARNING] Relative humidity exceeds 80%: High risk for fungal spore germination (Pyricularia oryzae). Monitor lower leaves closely.")

        # Rule 2: Heavy Rain Forecast -> Delay Top-Dressing Fertilizer Application
        if weather.rainfall_probability_pct >= 60.0:
            fert_advice = "DELAY FERTILIZER APPLICATION (Rainfall Runoff Risk)"
            notes.append("[RAIN ALERT] Rain probability exceeds 60%: Delay top-dressing Urea/MOP applications by 48 hours to prevent nutrient leaching into waterways.")

        # Rule 3: High Temperature -> Irrigation & Water Review
        if weather.temperature_c >= 32.0:
            irrigation_adv = "IRRIGATION REVIEW (Heat Stress Risk)"
            notes.append("[TEMP ALERT] Temperature exceeds 32C: Maintain standing water depth (3-5 cm) to cushion panicle development against thermal stress.")

        if not notes:
            notes.append("[INFO] Environmental conditions are optimal for standard cultivation practices.")

        return SeasonalAdvisory(
            fungal_risk_alert=fungal_alert,
            fertilizer_timing_advice=fert_advice,
            irrigation_advice=irrigation_adv,
            advisory_notes=notes
        )


class WeatherService:
    """
    High-level Weather & Seasonal Intelligence service.
    """

    def __init__(self, provider: Optional[IWeatherProvider] = None):
        self.provider = provider if provider else MockSriLankanWeatherProvider()

    def get_context_and_advisory(self, location: str = "North Central Province"):
        weather = self.provider.get_weather(location=location)
        advisory = SeasonAdvisor.evaluate(weather)
        return weather, advisory
