"""
SynthesisAgent Implementation
Agentic Pattern 3: Swarm Collaboration Pattern.
Combines outputs from multiple specialized agents (Diagnostic, Fertilizer, General) and web search
into a single, coherent, highly accurate final answer.
"""

from typing import Optional, Any, List, Dict
from core.agent_messages import DiagnosticResult, FertilizerRecommendation, ReflectionResult
from core.agents.base_agent import BaseAgent
from config.model_provider import get_reasoning_model

class SynthesisAgent(BaseAgent):
    """
    Acts as the 'Team Lead' in the Swarm Architecture.
    Reviews the drafts generated by DiagnosticAgent, FertilizerAgent, and General queries.
    Synthesizes a final, unified answer resolving any conflicting information.
    """

    def __init__(self):
        super().__init__(name="SynthesisAgent", model=None)

    def synthesize(
        self,
        user_query: str,
        diagnostic_info: Optional[Any] = None,
        fertilizer_info: Optional[Any] = None,
        general_info: Optional[Any] = None,
        reflection_result: Optional[Any] = None,
        conversation_history: Optional[List[Dict[str, str]]] = None
    ) -> str:
        """Zero-latency Local Synthesizer: formats agent results directly into markdown in 0ms."""
        return "".join(list(self.synthesize_stream(
            user_query,
            diagnostic_info,
            fertilizer_info,
            general_info,
            reflection_result,
            conversation_history=conversation_history
        )))

    def synthesize_stream(
        self,
        user_query: str,
        diagnostic_info: Optional[Any] = None,
        fertilizer_info: Optional[Any] = None,
        general_info: Optional[Any] = None,
        reflection_result: Optional[Any] = None,
        weather_info: Optional[Any] = None,
        final_synthesis: Optional[str] = None,
        conversation_history: Optional[List[Dict[str, str]]] = None
    ):
        """Zero-latency Conversational Streamer: Uses ConversationExperienceEngine for organic ChatGPT/Claude AI dialogue."""
        from core.synthesis.conversation_experience_engine import ConversationExperienceEngine

        conversational_text = ConversationExperienceEngine.compose_conversation(
            user_query=user_query,
            diagnostic_info=diagnostic_info,
            fertilizer_info=fertilizer_info,
            weather_info=weather_info,
            general_info=general_info,
            reflection_result=reflection_result,
            final_synthesis=final_synthesis,
            conversation_history=conversation_history,
        )

        if conversational_text.strip():
            yield conversational_text

    def process(self, message: any) -> any:
        """Required by BaseAgent, but unused in SynthesisAgent which uses synthesize() directly."""
        pass
